### ISSUE TITLE
[Feature request] Collapse duplicate URLs with different hashes

### ISSUE THREAD

**Issue by chocolateboy** [PKxk8J/click-tab-uniq#31]
(Thanks for this addon and ClickTabSort!)

I often end up with multiple copies of the same URL when deduping with this addon e.g.:

- https://github.com/PKxk8J/click-tab-uniq
- https://github.com/PKxk8J/click-tab-uniq#readme
- https://github.com/PKxk8J/click-tab-uniq#-messaging

Ideally, I'd like these to be collapsed into one URL, either by default, or as an option (to handle sites which (ab)use [fragment identifiers](https://en.wikipedia.org/wiki/Fragment_identifier) for navigation or state).

**Comment by PKxk8J** [comment]
Thank you for your request.
I added `URL without Hash` option at version 2.2.0.

**Comment by chocolateboy** [comment]
Thanks!
